### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by MaxRichter** [testdrivenio/falcon-celery#1]
Hi,

I tried to run the project in docker compose and got the following after after I executed `docker-compose up -d --build`.
Result:

```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
Did I run it correctly or have the wrong version of Docker?

**Comment by mjhea0** [comment]
Which version of Docker are you using?

Compose file version 3.5 only works with Docker version 17.12.0+. https://docs.docker.com/compose/compose-file/compose-versioning/

**Comment by mjhea0** [comment]
Closing this.

**Comment by MaxRichter** [comment]
I am using Docker 18.03.1-ce, I identified the error.
It was due to the Docker-Compose version that I have used. I installed the one from Ubuntu's apt, but this does not work.

What works is installing directly from GitHub with: 
> https://github.com/docker/compose/releases/download/1.21.2/docker-compose
